version: '2'

services:
  web:
    image: {{cookiecutter.project_slug}}_web
    build: ./web/
    # Expose ports without publishing them
    ports:
      - "8000:8000"
    links:
      - db:db
    env_file: .env.dev
    volumes:
      - ./web:/usr/src/app
      - web_public_dev:/public:rw
    depends_on:
      - db
    command: /run_server.sh local

  db:
    image: {{cookiecutter.project_slug}}_db
    build: ./db/
    env_file: .env.dev
    volumes:
      - db_data_dev:/var/lib/postgresql/data:rw
      - db_backup_dev:/backups
      - web_public_dev:/public:rw
    # Expose ports without publishing them
    expose:
      - "5432"

volumes:
  db_data_dev:
    driver: local
  db_backup_dev:
    driver: local
  web_public_dev:
    driver: local